routes/web.php
<?php

use App\Http\Controllers\Blog\CategoryController;
use App\Http\Controllers\Blog\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::resource('/rest', 'App\Http\Controllers\RestTestController')->names('restTest');
//Route::resource('posts', 'App\Http\Controllers\Blog\PostController')->names('blog.posts');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//Route::group(['prefix' => 'blog'], function (){
//    Route::resource('posts', PostController::class)->names('blog.posts');
//});

Route::group(['prefix' => 'blog'], function () {
    //BlogCategory
    $methods = ['index', 'edit', 'store', 'create', 'update'];
    Route::resource('categories', CategoryController::class)->only($methods)->names('blog.categories');

    //BlogPost
    Route::resource('posts', PostController::class)->names('blog.posts');

});

app/Http/Controllers/Blog/BaseController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

abstract class BaseController extends Controller
{
    //для загальних моментів для дочірніх класів
    /**
     *
     */
    public function __construct()
    {
    }
}

app/Http/Controllers/Blog/CategoryController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Requests\BlogCategoryCreateRequest;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Models\BlogCategory;
use App\Repositories\BlogCategoryRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Str;

class CategoryController extends BaseController
{
    /**
     * @var BlogCategoryRepository
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        parent::__construct();

        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }


    public function index()
    {
        $paginator = $this->blogCategoryRepository->getAllWithPaginate(5);

        return view('blog.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        $item = new BlogCategory();

//        $listCategory = $this->blogCategoryRepository->getForcomboBox();

        return view('blog.categories.add', compact('item'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();
        $item = (new BlogCategory())->create($data);

        if ($item) {
            return redirect()->route('blog.categories.edit', [$item->id])->with(['success' => 'Збережено успішно']);
        } else {
            return back()->withErrors(['msg' => 'Помилка збереження'])->withInput();
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @param BlogCategoryRepository $categoryRepository
     *
     * @return Application|Factory|View|\Illuminate\Foundation\Application|Response|\Illuminate\View\View
     */
    public function edit($id, BlogCategoryRepository $categoryRepository)
    {
        $item = $this->blogCategoryRepository->getEdit($id);
        if (empty($item)) {
            abort(404);
        }

        $listCategory = $this->blogCategoryRepository->getForcomboBox();

        return view('blog.categories.edit', compact('item', 'listCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {
        $item = $this->blogCategoryRepository->getEdit($id);

        if (empty($item)) {
            return back()->withErrors(['msg' => "Запис id=[{$id}] не знайдено"])->withInput();
        }

        $data = $request->all();
        $result = $item->update($data);

        if ($result) {
            return redirect()->route('blog.categories.edit', $item->id)->with(['success' => 'Збережено успішно']);
        } else {
            return back()->withErrors(['msg' => "Запис не збережено"])->withInput();
        }
    }

}

app/Http/Controllers/Blog/PostController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Requests\Request\BlogPostCreateRequest;
use App\Http\Requests\Request\BlogPostUpdateRequest;
use App\Models\BlogPost;
use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PostController extends BaseController
{

    private $blogPostRepository;

    /**
     * @var BlogCategoryRepository|BlogCategoryRepository&Application|Application|\Illuminate\Foundation\Application|mixed
     */
    private $blogCategoryRepository;

    public function __construct()
    {
        parent::__construct();
        $this->blogPostRepository = app(BlogPostRepository::class);
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\View\View
     */
    public function index()
    {
        $paginator = $this->blogPostRepository->getAllWithPaginate(10);

        return view('blog.posts.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        $item = new BlogPost();
        $listCategory = $this->blogCategoryRepository->getForcomboBox();

        return view('blog.posts.edit', compact('item', 'listCategory'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(BlogPostCreateRequest $request)
    {
        $data = $request->input();
        $item = (new BlogPost())->create($data);

        if ($item) {
            return redirect()->route('blog.posts.edit', [$item->id])->with(['success' => 'Збережено успішно']);
        } else {
            return back()->withErrors(['msg' => 'Помилка збереження'])->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     */
    public function show($id)
    {
        $item = $this->blogPostRepository->getShow($id);
        return view('blog.posts.show',compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     */
    public function edit($id)
    {
        $item = $this->blogPostRepository->getEdit($id);
        if (empty($item)) {
            abort(404);
        }

        $listCategory = $this->blogCategoryRepository->getForcomboBox();

        return view('blog.posts.edit', compact('item', 'listCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */

    public function update(BlogPostUpdateRequest $request, $id)
    {
        $item = $this->blogPostRepository->getEdit($id);

        if (empty($item)) {
            return back()
                ->withErrors(['msg' => "Запис id=[{$id}] не знайдено"])
                ->withInput();
        }

        $data = $request->all();
        $result = $item->update($data);

        if ($result) {
            return redirect()->route('blog.posts.edit', $item->id)->with(['success' => 'Збережено успішно']);
        } else {
            return back()->withErrors(['msg' => "Запис не збережено"])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function destroy($id)
    {
//        $result = BlogPost::destroy($id);
        $result = BlogPost::find($id)->forceDelete();

        if ($result){
            return redirect()->route('blog.posts.index')->with(['success' => "Запис id[$id] видалено"]);
        }else{
            return back()->withErrors(['msg' => 'Помилка видалення']);
        }
    }
}

resources/views/blog/posts/edit.blade.php
@extends('layouts.app')

@section('content')

    @if($item->exists)
        <form method="POST" action="{{route('blog.posts.update', $item->id)}}">
            @method('PATCH')
            @else
                <form method="POST" action="{{route('blog.posts.store')}}">
                    @endif
                    @csrf
                    <div class="container">
                        @include('blog.includes.result_messages')
                        <div class="row justify-content-center">
                            <div class="col-md-8">
                                @include('blog.posts.includes.edit_main_bloc')
                            </div>
                            <div class="col-md-3">
                                @include('blog.posts.includes.edit_add_bloc')
                            </div>
                        </div>
                    </div>
                </form>

                @if($item->exists)
                    <div class="container">
                        <form method="POST" action="{{route('blog.posts.destroy', $item->id)}}">
                            @method('DELETE')
                            @csrf
                            <div class="row justify-content-center">
                                <div class="col-md-8">
                                    <div class="card card-block">
                                        <div class="card-body ml-auto">
                                            <button type="submit" class="btn btn-danger">
                                                Видалити
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                @endif
@endsection

resources/views/blog/posts/show.blade.php
@extends('layouts.app')

@section('content')

    @if($item->exists)

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    {{--                    @include('blog.posts.includes.edit_main_bloc')--}}
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card-title"></div>
                                    <ul class="nav nav-tabs" role="tablist">
                                        <li class="nav-item">
                                            <a class="active nav-link" data-toggle="tab" href="#maindata" role="tab">Основні
                                                дані</a>
                                        </li>
                                    </ul>
                                    <br>
                                    <div class="tab-content">
                                        <div class="tab-pane active" id="maindata" role="tabpanel">
                                            <div class="form-group">
                                                <label for="title">Заголовок</label>
                                                <p id="title" class="form-control">{{$item->title}}</p>
                                            </div>

                                            <div class="form-group">
                                                <label for="slug">Slug</label>
                                                <p id="slug" class="form-control">{{$item->slug}}</p>
                                            </div>

                                            <div class="form-group">
                                                <label for="category_id">Категорія</label>
                                                <p id="category_id" class="form-control">{{$item->category->title}}</p>

                                            </div>

                                            <div class="form-group">
                                                <label for="description">Опис</label>
                                                <p id="description" class="form-control">{{$item->description}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-3">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <form method="POST" action="{{route('blog.posts.edit', $item->id)}}">
                                        @method('GET')
                                        @csrf
                                        <button type="submit" class="btn btn-outline-primary">
                                            Редагувати
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <form method="POST" action="{{route('blog.posts.destroy', $item->id)}}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-danger">
                                            Видалити
                                        </button>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <ul class="list-unstyled">
                                        <li>ID: {{$item->id}}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">Створено</label>
                                        <input value="{{$item->created_at}}" class="form-control" type="text"
                                               disabled>
                                    </div>
                                    <div class="form-group">
                                        <label for="title">Змінено</label>
                                        <input value="{{$item->updated_at}}" class="form-control" type="text"
                                               disabled>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

    @endif
@endsection